---
exclude_paths:
  - "examples/**"
  - "__tests__/**"
  - "scripts/**"
  - "forge-sql-orm-extra/scripts//**"
  - "forge-sql-orm-cli/__tests__/**"
  - "forge-sql-orm-extra/__tests__/**"
  - "forge-sql-orm-cli/src/actions/generate-models.ts"
  - "vitest.config.mjs"