/**
 * This file was auto-generated by forge-sql-orm
 * Generated at: 2026-02-03T12:55:11.684Z
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * Any changes will be overwritten on next generation
 */

export * from "./schema";

export interface VersionFieldMetadata {
  fieldName: string;
}

export interface TableMetadata {
  tableName: string;
  versionField: VersionFieldMetadata;
}

export type AdditionalMetadata = Record<string, TableMetadata>;

export const additionalMetadata: AdditionalMetadata = {};
